### ISSUE TITLE
Unending shimmering if user open the app with restore data from storage

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/telenova-web-app#201]
When user open the app with restore from telegram security storage it will open main page with unendin shimmering:

<img src="https://github.com/user-attachments/assets/35f36794-0404-444a-ada1-fe31dda06138" data-canonical-src="https://github.com/user-attachments/assets/35f36794-0404-444a-ada1-fe31dda06138" width="200" />

Case:
1. Login on two devices
2. On device_a - change the password
3. Log in on device_b
4. When will trigger restore flow - enter the password

Expected result:
Successfull log in

Actual result:
Unending loading state on main page

https://github.com/user-attachments/assets/02fdb7be-1b68-43c7-be67-f517035bea27

**Comment by tuul-wq** [comment]
Fixed in current `dev`

**Comment by stepanLav** [comment]
Status verification: ✅
